[pytest]
markers =
    login: login tests
    user_guest: tests for unauthorized users
    user_auth: tests for authorized users
    negative: negative tests
    need_review: special mark for reviewers on Stepik